name: Exile
version: ${project.version}
main: dev.mja00.exile.Exile
api-version: 1.13
authors: [mja00]
description: Allows you to exile players to a configured location
website: https://mja00.dev
commands:
  exile:
    description: Player exile control. Using /exile <player> <reason> it will notify everyone with exile.notify of the report. Using /exile approve <player> will exile the player specified, teleporting them to the configred locatino.
permissions:
  exile.notify:
    description: Allows the player to be notified of Exile reports
  exile.approve:
    description: Allows the player to approve exiles which will then exile them
  exile.edit:
    description: Allows the player to edit the config using commands
  exile.immune:
    description: Makes the player immune to exile reports
